baseURL = "http://alisonwalters.io"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Alison"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "/#about"
weight = 2
[[menu.main]]
name = "Projects"
url = "/#service"
weight = 3
[[menu.main]]
name = "Resume"
url = "/#resume"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "/#about"
weight = 1

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

footerButtonTarget = "/contact"
footerButtonText = "Get in Touch"
footerCallToAction = "Let's Work Together"
footerLogo = "images/contact/widget-logo.png"
footerTopTitle = "Contact me"

headerButtonTarget = "/contact"
headerButtonText = "Let's Chat"

[params.address]
address = "Virginia, USA"
email = "akwalters31@gmail.com"
openingHours = "Contact whenever!"
phone = "(703) 677 7607"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "37.2284"
longitude = "80.4234"
pinImage = "images/pin.png"

# Socail icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 1

